---
version: '3.6'
services:
  chrome:
    image: selenium/standalone-chrome-debug:latest
    restart: unless-stopped
    container_name: ddev-${DDEV_SITENAME}-chrome
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - ddev-global-cache:/mnt/ddev-global-cache
      - ".:/mnt/ddev_config"
      - /dev/shm:/dev/shm
    external_links:
      - "ddev-router:${DDEV_HOSTNAME}"
    cap_add:
      - SYS_ADMIN
    ports:
      # VNC port
      - '5900:5900'
networks:
  default:
    external:
      name: ddev_default
